# @package _group_
_target_: mbrl.models.GaussianMLP
device: ${device}
num_layers: 2
in_size: ???
out_size: ???
ensemble_size: 7
hid_size: 64
deterministic: false
propagation_method: fixed_model
learn_logvar_bounds: false  # so far this works better
activation_fn_cfg:
  _target_: torch.nn.SiLU
